// ============================================================================
// Flicker ASM Export — sjasmplus-compatible ASM source for Gigascreen and RGB3
// ============================================================================

/**
 * Generates sjasmplus-compatible ASM source for Gigascreen (.img) display.
 * Uses Pentagon 128K dual-screen capability (banks 5 and 7).
 * Alternates between screens each frame for 25Hz flicker (50Hz / 2 frames).
 * @param {Uint8Array} imgData - 13824 bytes (2 × 6912)
 * @param {string} baseName - Base filename for SAVESNA output
 * @returns {string} Complete ASM source code
 */
function generateGigascreenAsm(imgData, baseName = 'gigascreen', embedData = true) {
  if (!imgData || imgData.length < 13824) return null;

  const frame1 = Array.from(imgData.slice(0, 6912));
  const frame2 = Array.from(imgData.slice(6912, 13824));

  function formatDbLines(data, bytesPerLine) {
    const lines = [];
    for (let i = 0; i < data.length; i += bytesPerLine) {
      const chunk = data.slice(i, Math.min(i + bytesPerLine, data.length));
      lines.push('    DB ' + chunk.map(b => '#' + b.toString(16).toUpperCase().padStart(2, '0')).join(','));
    }
    return lines.join('\n');
  }

  const asm = [];

  // === Header ===
  asm.push('; ============================================================================');
  asm.push('; Gigascreen viewer — Pentagon 128K');
  asm.push('; Generated by SpectraLab');
  asm.push('; sjasmplus compatible source');
  asm.push(';');
  asm.push('; Uses dual-screen banking: frame 1 in bank 5 (#4000), frame 2 in bank 7');
  asm.push('; Port #7FFD bit 3 selects displayed screen: 0=bank 5, 1=bank 7');
  asm.push('; Alternates each frame for 25Hz flicker effect');
  asm.push('; IM2 vector table at #8000 (fixed RAM), code at #8200');
  asm.push('; ============================================================================');
  asm.push('');
  asm.push('    DEVICE ZXSPECTRUM128');
  asm.push('    ORG #8200           ; After IM2 vector table at #8000-#8100');
  asm.push('');

  // === Constants ===
  asm.push('PORT_7FFD    EQU #7FFD');
  asm.push('BANK5_SCREEN EQU #10      ; Bit 4=1 (ROM1), bit 3=0 (screen bank 5)');
  asm.push('BANK7_SCREEN EQU #18      ; Bit 4=1 (ROM1), bit 3=1 (screen bank 7)');
  asm.push('');

  // === Initialization ===
  asm.push('; ============================================================================');
  asm.push('; Initialization');
  asm.push('; ============================================================================');
  asm.push('Start:');
  asm.push('    DI');
  asm.push('    LD SP,#7FFE');
  asm.push('');
  asm.push('    ; Select bank 0 in slot 3, screen bank 5');
  asm.push('    LD A,BANK5_SCREEN');
  asm.push('    LD BC,PORT_7FFD');
  asm.push('    OUT (C),A');
  asm.push('');
  asm.push('    ; Copy frame 1 to bank 5 (#4000)');
  asm.push('    LD HL,Frame1Data');
  asm.push('    LD DE,#4000');
  asm.push('    LD BC,6912');
  asm.push('    LDIR');
  asm.push('');
  asm.push('    ; Page in bank 7 to slot 3');
  asm.push('    LD A,#17              ; Bank 7 in slot 3, screen=5');
  asm.push('    LD BC,PORT_7FFD');
  asm.push('    OUT (C),A');
  asm.push('');
  asm.push('    ; Copy frame 2 to bank 7 screen area');
  asm.push('    ; Bank 7 paged to #C000, screen is at offset 0 within bank = #C000');
  asm.push('    LD HL,Frame2Data');
  asm.push('    LD DE,#C000');
  asm.push('    LD BC,6912');
  asm.push('    LDIR');
  asm.push('');
  asm.push('    ; Restore normal paging: bank 0 in slot 3');
  asm.push('    LD A,BANK5_SCREEN');
  asm.push('    LD BC,PORT_7FFD');
  asm.push('    OUT (C),A');
  asm.push('');
  asm.push('    ; Set border to black');
  asm.push('    XOR A');
  asm.push('    OUT (#FE),A');
  asm.push('');

  // === IM2 Setup (in fixed RAM, not banked area) ===
  asm.push('    ; Setup IM2 interrupt handler at #8000 (fixed RAM)');
  asm.push('    LD HL,#8000');
  asm.push('    LD DE,#8001');
  asm.push('    LD BC,256');
  asm.push('    LD (HL),#80');
  asm.push('    LDIR');
  asm.push('');
  asm.push('    ; ISR at #8080: EI + RETI');
  asm.push('    LD A,#FB             ; EI opcode');
  asm.push('    LD (#8080),A');
  asm.push('    LD A,#ED             ; RETI prefix');
  asm.push('    LD (#8081),A');
  asm.push('    LD A,#4D             ; RETI suffix');
  asm.push('    LD (#8082),A');
  asm.push('');
  asm.push('    LD A,#80');
  asm.push('    LD I,A');
  asm.push('    IM 2');
  asm.push('    EI');
  asm.push('');

  // === Main Loop ===
  asm.push('; ============================================================================');
  asm.push('; Main Loop - alternate screens each frame');
  asm.push('; ============================================================================');
  asm.push('MainLoop:');
  asm.push('    HALT                  ; Wait for frame start');
  asm.push('    ; Switch to screen bank 5 immediately (during border)');
  asm.push('    LD A,BANK5_SCREEN');
  asm.push('    LD BC,PORT_7FFD');
  asm.push('    OUT (C),A');
  asm.push('');
  asm.push('    HALT                  ; Wait for frame start');
  asm.push('    ; Switch to screen bank 7 immediately (during border)');
  asm.push('    LD A,BANK7_SCREEN');
  asm.push('    LD BC,PORT_7FFD');
  asm.push('    OUT (C),A');
  asm.push('');
  asm.push('    JR MainLoop');
  asm.push('');

  // === Data section ===
  asm.push('; ============================================================================');
  asm.push('; Data');
  asm.push('; ============================================================================');
  asm.push('');
  asm.push('Frame1Data:              ; 6912 bytes');
  if (embedData) {
    asm.push(formatDbLines(frame1, 16));
  } else {
    asm.push(`    INCBIN "${baseName}.img", 0, 6912`);
  }
  asm.push('');
  asm.push('Frame2Data:              ; 6912 bytes');
  if (embedData) {
    asm.push(formatDbLines(frame2, 16));
  } else {
    asm.push(`    INCBIN "${baseName}.img", 6912, 6912`);
  }
  asm.push('');
  asm.push('    SAVESNA "' + baseName + '.sna",Start');
  asm.push('');

  return { asm: asm.join('\n') };
}

/**
 * Generates sjasmplus-compatible ASM source for RGB3 (.3) display.
 * Uses ultra-fast unrolled LD HL,nn : PUSH HL technique with embedded bitmap data.
 * Cycles through 3 monochrome bitmaps with R, G, B color attributes.
 * Achieves tear-free 50fps: 64512T bitmap + ~5000T attrs = ~70000T (under 71680T frame)
 * @param {Uint8Array} rgb3Data - 18432 bytes (3 × 6144)
 * @param {string} baseName - Base filename for SAVESNA output
 * @returns {string} Complete ASM source code
 */
function generateRgb3Asm(rgb3Data, baseName = 'rgb3') {
  if (!rgb3Data || rgb3Data.length < 18432) return null;

  const frame1 = rgb3Data.slice(0, 6144);      // Red
  const frame2 = rgb3Data.slice(6144, 12288);  // Green
  const frame3 = rgb3Data.slice(12288, 18432); // Blue

  /**
   * Generate unrolled LD HL,nn : PUSH HL sequence for 6144 bytes.
   * PUSH decrements SP first then writes, so we emit last bytes first.
   * Each pair: LD HL,nn (10T) + PUSH HL (11T) = 21T
   * 3072 pairs × 21T = 64512T (under one frame!)
   */
  function generateUnrolledCopy(frameData, label, saveSPLabel) {
    const lines = [];
    lines.push(label + ':');
    lines.push('    DI');
    lines.push('    LD (' + saveSPLabel + '+1),SP');
    lines.push('    LD SP,SCREEN_BITMAP + BITMAP_SIZE');
    lines.push('');
    // PUSH decrements SP then writes, so push last addresses first
    for (let i = 6142; i >= 0; i -= 2) {
      const lo = frameData[i];
      const hi = frameData[i + 1];
      const value = (hi << 8) | lo;
      const hex = '#' + value.toString(16).toUpperCase().padStart(4, '0');
      lines.push('    LD HL,' + hex + ' : PUSH HL');
    }
    lines.push('');
    lines.push(saveSPLabel + ':');
    lines.push('    LD SP,0');
    lines.push('    EI');
    lines.push('    RET');
    return lines.join('\n');
  }

  const asm = [];

  // === Header ===
  asm.push('; ============================================================================');
  asm.push('; RGB3 Tricolor viewer — Pentagon 128K');
  asm.push('; Generated by SpectraLab');
  asm.push('; sjasmplus compatible source');
  asm.push(';');
  asm.push('; Ultra-fast unrolled copy: LD HL,nn : PUSH HL (10T + 11T = 21T per 2 bytes)');
  asm.push('; Bitmap: 3072 pairs × 21T = 64512T');
  asm.push('; Attrs: ~5000T');
  asm.push('; Total: ~70000T per frame (under 71680T — tear-free 50fps!)');
  asm.push(';');
  asm.push('; Code size: ~37KB (3 frames × 12KB unrolled copy)');
  asm.push('; IM2 vector table at #5B00 (after screen, code at #6000-#F400)');
  asm.push('; ============================================================================');
  asm.push('');
  asm.push('    DEVICE ZXSPECTRUM128');
  asm.push('    ORG #6000');
  asm.push('');

  // === Constants ===
  asm.push('; Attribute values: INK on BLACK paper, BRIGHT');
  asm.push('ATTR_RED   EQU #42       ; Bright red ink (2) on black');
  asm.push('ATTR_GREEN EQU #44       ; Bright green ink (4) on black');
  asm.push('ATTR_BLUE  EQU #41       ; Bright blue ink (1) on black');
  asm.push('');
  asm.push('SCREEN_BITMAP EQU #4000');
  asm.push('SCREEN_ATTRS  EQU #5800');
  asm.push('BITMAP_SIZE   EQU 6144');
  asm.push('ATTRS_SIZE    EQU 768');
  asm.push('');

  // === Initialization ===
  asm.push('; ============================================================================');
  asm.push('; Initialization');
  asm.push('; ============================================================================');
  asm.push('Start:');
  asm.push('    DI');
  asm.push('    LD SP,#5FFE');
  asm.push('');
  asm.push('    ; Standard 128K config');
  asm.push('    XOR A');
  asm.push('    LD BC,#7FFD');
  asm.push('    OUT (C),A');
  asm.push('');
  asm.push('    ; Clear screen');
  asm.push('    LD HL,SCREEN_BITMAP');
  asm.push('    LD DE,SCREEN_BITMAP+1');
  asm.push('    LD BC,6911');
  asm.push('    LD (HL),0');
  asm.push('    LDIR');
  asm.push('');
  asm.push('    ; Set border to black');
  asm.push('    XOR A');
  asm.push('    OUT (#FE),A');
  asm.push('');

  // === IM2 Setup (at #5B00, just after screen attrs, before code at #6000) ===
  asm.push('    ; Setup IM2 interrupt handler at #5B00 (after screen, before code)');
  asm.push('    LD HL,#5B00');
  asm.push('    LD DE,#5B01');
  asm.push('    LD BC,256');
  asm.push('    LD (HL),#5B');
  asm.push('    LDIR');
  asm.push('');
  asm.push('    ; ISR at #5B5B: EI + RETI');
  asm.push('    LD A,#FB             ; EI opcode');
  asm.push('    LD (#5B5B),A');
  asm.push('    LD A,#ED             ; RETI prefix');
  asm.push('    LD (#5B5C),A');
  asm.push('    LD A,#4D             ; RETI suffix');
  asm.push('    LD (#5B5D),A');
  asm.push('');
  asm.push('    LD A,#5B');
  asm.push('    LD I,A');
  asm.push('    IM 2');
  asm.push('    EI');
  asm.push('');

  // === Main Loop ===
  asm.push('; ============================================================================');
  asm.push('; Main Loop - cycle through R, G, B frames');
  asm.push('; Each frame: HALT + CopyFrameN + FillAttrs < 71680T (tear-free!)');
  asm.push('; ============================================================================');
  asm.push('MainLoop:');
  asm.push('    ; === Frame 1: RED ===');
  asm.push('    HALT');
  asm.push('    CALL CopyFrame1');
  asm.push('    LD A,ATTR_RED');
  asm.push('    CALL FillAttrs');
  asm.push('');
  asm.push('    ; === Frame 2: GREEN ===');
  asm.push('    HALT');
  asm.push('    CALL CopyFrame2');
  asm.push('    LD A,ATTR_GREEN');
  asm.push('    CALL FillAttrs');
  asm.push('');
  asm.push('    ; === Frame 3: BLUE ===');
  asm.push('    HALT');
  asm.push('    CALL CopyFrame3');
  asm.push('    LD A,ATTR_BLUE');
  asm.push('    CALL FillAttrs');
  asm.push('');
  asm.push('    JP MainLoop');
  asm.push('');

  // === Fill Attributes Routine ===
  asm.push('; ============================================================================');
  asm.push('; Fill all 768 attributes with value in A');
  asm.push('; Uses stack for speed (~5000 T-states)');
  asm.push('; ============================================================================');
  asm.push('FillAttrs:');
  asm.push('    DI');
  asm.push('    LD (RestoreAttrSP+1),SP');
  asm.push('    LD H,A');
  asm.push('    LD L,A               ; HL = attr byte doubled');
  asm.push('    LD SP,SCREEN_ATTRS + ATTRS_SIZE');
  asm.push('');
  asm.push('    ; 768 bytes / 2 = 384 PUSHes');
  asm.push('    ; Unroll 8 PUSHes per loop = 48 iterations');
  asm.push('    LD B,48');
  asm.push('.attrLoop:');
  asm.push('    PUSH HL : PUSH HL : PUSH HL : PUSH HL');
  asm.push('    PUSH HL : PUSH HL : PUSH HL : PUSH HL');
  asm.push('    DJNZ .attrLoop');
  asm.push('');
  asm.push('RestoreAttrSP:');
  asm.push('    LD SP,0');
  asm.push('    EI');
  asm.push('    RET');
  asm.push('');

  // === Unrolled copy routines (3 × 12KB = ~37KB total) ===
  asm.push('; ============================================================================');
  asm.push('; Unrolled bitmap copy routines');
  asm.push('; Each routine: 3072 × (LD HL,nn : PUSH HL) = 64512T');
  asm.push('; Data is embedded as immediate values — maximum speed!');
  asm.push('; ============================================================================');
  asm.push('');
  asm.push(generateUnrolledCopy(frame1, 'CopyFrame1', 'SaveSP1'));
  asm.push('');
  asm.push(generateUnrolledCopy(frame2, 'CopyFrame2', 'SaveSP2'));
  asm.push('');
  asm.push(generateUnrolledCopy(frame3, 'CopyFrame3', 'SaveSP3'));
  asm.push('');
  asm.push('    SAVESNA "' + baseName + '.sna",Start');
  asm.push('');

  // RGB3 always has data embedded in LD HL,nn instructions - no INCBIN option
  return { asm: asm.join('\n') };
}

/**
 * Exports Gigascreen (.img) as sjasmplus ASM source file.
 */
function exportGigascreenAsm() {
  if (currentFormat !== FORMAT.GIGASCREEN || !screenData || screenData.length < 13824) {
    alert('Export ASM is only available for Gigascreen (.img) format.');
    return;
  }

  let baseName = 'gigascreen';
  if (currentFileName) {
    const fileName = currentFileName.includes('/')
      ? currentFileName.substring(currentFileName.lastIndexOf('/') + 1)
      : currentFileName;
    baseName = fileName.replace(/\.[^.]+$/, '');
  }

  const embedChk = document.getElementById('editorEmbedDataChk');
  const embedData = embedChk ? embedChk.checked : true;

  const result = generateGigascreenAsm(screenData, baseName, embedData);
  if (!result) return;

  const blob = new Blob([result.asm], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = baseName + '.asm';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Exports RGB3 (.3) as sjasmplus ASM source file.
 */
function exportRgb3Asm() {
  if (currentFormat !== FORMAT.RGB3 || !screenData || screenData.length < 18432) {
    alert('Export ASM is only available for RGB3 (.3) format.');
    return;
  }

  let baseName = 'rgb3';
  if (currentFileName) {
    const fileName = currentFileName.includes('/')
      ? currentFileName.substring(currentFileName.lastIndexOf('/') + 1)
      : currentFileName;
    baseName = fileName.replace(/\.[^.]+$/, '');
  }

  // RGB3 always embeds data in code (LD HL,nn) - checkbox is ignored
  const result = generateRgb3Asm(screenData, baseName);
  if (!result) return;

  const blob = new Blob([result.asm], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = baseName + '.asm';

  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
